packages:
  - apps/*
  - packages/*
  - services/*

catalog:
  '@biomejs/biome': 2.3.14
  'typescript': 5.9.3
  'vitest': ^3.0.0
  '@vitest/ui': ^3.0.0
  '@vitest/coverage-v8': ^3.0.0
  '@testing-library/react': ^16.0.0
  '@testing-library/react-native': ^13.0.0
  'tsup': ^8.4.0

nodeLinker: isolated
onlyBuiltDependencies:
  - esbuild
  - sharp
